version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  mongodb:
    image: mongo:6
    container_name: mongo-db
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb-data:
    driver: local
